### PR TITLE
Cleaning, instructions for non-composer users, better example

### PR DESCRIPTION
**Pull request by JamesCullum**
- Indentation improved, it was pretty hard to read
- Composer appears to be an overkill for me for only having CURL as
  dependancy which is pretty common already. Therefore added instructions
  on how to avoid it.
- The example was neither easy to read, nor explained in any way. This
  minified version shows the structure and workflow better.

### CODE REVIEW

**Comment by dainnilsson** [comment]
Thanks. Could you rebase the changes into two separate pull requests? One for the non-composer stuff, and one for the replaced example? Regarding indentation, please follow the style used in the rest of the project for consistency (2 spaces for indentation, curly braces on the same line as if/else, etc.).

**Comment by JamesCullum** [comment]
Why shall i split it up into two seperate pull request? Maybe its because im not too used to GitHub so maybe you can explain it to me as its the same whether or not its done in one or two steps.
Ill take another look at the indentation.

**Comment by dainnilsson** [comment]
In general it's best to keep pull requests as small scoped as possible, to allow the maintainer to reason about each PR independently. For example, the changes to make it easier to use the library without Composer are quite simple and mainly involve documentation. If those changes were in a separate PR then that would probably get merged right away, since it's a "no-brainer". Now that feature is being held back by a completely unrelated one, because they are in the same PR.

The same goes for doing multiple things in a single commit. Breaking things up makes it simple for the maintainer to see what the actual changes are. When functionality is changed, and things like indentation are changed in the same commit, the diff becomes much more difficult to parse.

**Comment by JamesCullum** [comment]
Ah ok, thanks for the explanation, that does help me! :+1:

**Pull request closed without merging**
