### PR TITLE
Better example

### PR DESCRIPTION
**Pull request by JamesCullum**
Long liveth the empire of the tabs for tis superior ov'r spaces. Thee
shalt not keepeth the war alive but spendeth time wisely.

### CODE REVIEW

**Comment by dainnilsson** [comment]
For the record: I have no strong opinion on tabs vs spaces, I'm generally fine with either. The issue was about consistent formatting within the project, which this still doesn't have, as it's now using 4-space indents instead of 2-space. If it's fine with you, how about I just fix the formatting myself after merging?

**Comment by JamesCullum** [comment]
Well 4 spaces at least look like a tab, 2 spaces is too close to be easy to read. You can change it yourself after merging, i dont feel comfortable changing it for the fifth time for such a nonsense topic.

**Comment by dainnilsson** [comment]
Here's the thing I'm having trouble understanding. You say yourself that it's a nonsense topic (I agree), yet you keep re-submitting this file with different formattings that are not what I've requested, and each time you bring up this same "nonsense topic" as the reason for not complying with the request. The only reason I asked that you fix it in the first place, is that I assumed it would be trivial for you to do and that you would prefer to do it yourself rather than have me immediately change your contribution after you submitted it, but really I'm fine either way.

As this is a new file, please state that the code is your own, and that you agree to contribute it under the license of the project (full text available in the COPYING file in the root of this repository).

**Comment by JamesCullum** [comment]
I know what you mean and its a good point. The main reason behind me re-submitting it multiple times is actually far more easy. The first time i just submitted it without noticing any pattern in your coding style as it just appeared to be very untidy. The second time i focused on doing two seperate pull requests (those obviously didnt work) as this appeared to be important to you while you made it sound like the space-tab-discussion is optional to you and you will merge it anyways. The third time i just submitted the documentation and the fourth time (this one) i wanted to comply to the spaces but thought that your "2 spaces" means that all indentation should be consistent in steps of two spaces. Therefore i thought these 4 spaces (as 2x2 spaces) was compliant to your pattern. I only realized from your last message that you really mean 2 spaces = 1 level. 
It should've been quite trivial but because it just feels very weird and ive never seen this coding style before i didnt really understand it or how important it is to you (thats why i keep telling its nonsense - denying multiple pull requests only because of tabs instead of spaces).

Cant we just pull it like that? For me it feels unnecessary to repeat the license after its already mentioned multiple times (readme & copying) and i do agree to share it like that (actually i thought thats the idea of open source collaboration - the license of the initial license is used for everything added or subtracted).

**Comment by dainnilsson** [comment]
I just needed you to state it here, which I interpret "and i do agree to share it like that" as, so consider that done. I've looked through the code, and I don't have anything else to remark on, so my plan is to test it out (actually run the code), merge it, and fix up the formatting. Probably some time next week.

**Comment by dainnilsson** [comment]
Tested, thank you.

**Pull request merged**
