### PR TITLE
Better example & indentation

### PR DESCRIPTION
**Pull request by JamesCullum**
- Indentation improved, it was pretty hard to read. Now used spaces
  instead of tabs, even though i consider it very bad practice.
- The example was neither easy to read, nor explained in any way. This
  minified version shows the structure and workflow better.

### CODE REVIEW

**Comment by dainnilsson** [comment]
The indentation is still using tabs. Please remove all the "revert" commits, those look like they weren't intentional?

**Comment by JamesCullum** [comment]
Yeah, my attempt on doing two seperate pull requests failed (two times).
I changed tabs to spaces in the config - file as it was yours and used spaces already, just so it keeps your coding style.
I prefer keeping the example using tabs and as this is no mix of tabs and spaces it is neither obvious to readers nor bad style. I consider two spaces instead of tabs bad practice and wont replace the tabs in the example. 

As this is a quite common discussion, please refer to http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

**Comment by dainnilsson** [comment]
You're right, it is a very common discussion. If you take a look at the top two answers in the link you've provided, you'll see that while one advocates spaces and the other tabs, they both agree that the most important thing is consistency within the project, which I agree with as well.

**Comment by JamesCullum** [comment]
Well it says "consistent throughout your code", not the whole project. Thats what i meant by having only one style per file but a different one in another file.

**Pull request closed without merging**
